// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcfvbojgbyedswsylmwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZnZib2pnYnllZHN3c3lsbXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NDYyNTQsImV4cCI6MjA4ODQyMjI1NH0.ovuTn3w3AyUzMenamQtJk7sSmg8xrcGXm7oL8hVUGJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});